//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <chat.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_chat_User_ids[2] =
{
    "::Ice::Object",
    "::chat::User"
};
const ::std::string iceC_chat_User_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendMessage",
    "sendPrivateMessage"
};
const ::std::string iceC_chat_User_sendMessage_name = "sendMessage";
const ::std::string iceC_chat_User_sendPrivateMessage_name = "sendPrivateMessage";

const ::std::string iceC_chat_chatRoom_ids[2] =
{
    "::Ice::Object",
    "::chat::chatRoom"
};
const ::std::string iceC_chat_chatRoom_ops[] =
{
    "Leave",
    "getUser",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "join",
    "listUsers",
    "postMessage"
};
const ::std::string iceC_chat_chatRoom_listUsers_name = "listUsers";
const ::std::string iceC_chat_chatRoom_join_name = "join";
const ::std::string iceC_chat_chatRoom_postMessage_name = "postMessage";
const ::std::string iceC_chat_chatRoom_getUser_name = "getUser";
const ::std::string iceC_chat_chatRoom_Leave_name = "Leave";

const ::std::string iceC_chat_chatRoomFactory_ids[2] =
{
    "::Ice::Object",
    "::chat::chatRoomFactory"
};
const ::std::string iceC_chat_chatRoomFactory_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newChatRoom"
};
const ::std::string iceC_chat_chatRoomFactory_newChatRoom_name = "newChatRoom";

const ::std::string iceC_chat_chatServer_ids[2] =
{
    "::Ice::Object",
    "::chat::chatServer"
};
const ::std::string iceC_chat_chatServer_ops[] =
{
    "getRoom",
    "getRooms",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newChatRoom",
    "registerFactory",
    "unregisterFactory"
};
const ::std::string iceC_chat_chatServer_getRooms_name = "getRooms";
const ::std::string iceC_chat_chatServer_getRoom_name = "getRoom";
const ::std::string iceC_chat_chatServer_newChatRoom_name = "newChatRoom";
const ::std::string iceC_chat_chatServer_registerFactory_name = "registerFactory";
const ::std::string iceC_chat_chatServer_unregisterFactory_name = "unregisterFactory";

}

bool
chat::User::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_User_ids, iceC_chat_User_ids + 2, s);
}

::std::vector<::std::string>
chat::User::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_chat_User_ids[0], &iceC_chat_User_ids[2]);
}

::std::string
chat::User::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::User::ice_staticId()
{
    static const ::std::string typeId = "::chat::User";
    return typeId;
}

/// \cond INTERNAL
bool
chat::User::_iceD_sendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_message;
    ::std::string iceP_fromWho;
    istr->readAll(iceP_message, iceP_fromWho);
    inS.endReadParams();
    this->sendMessage(::std::move(iceP_message), ::std::move(iceP_fromWho), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::User::_iceD_sendPrivateMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_message;
    ::std::string iceP_fromWho;
    istr->readAll(iceP_message, iceP_fromWho);
    inS.endReadParams();
    this->sendPrivateMessage(::std::move(iceP_message), ::std::move(iceP_fromWho), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::User::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_User_ops, iceC_chat_User_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_User_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendMessage(in, current);
        }
        case 5:
        {
            return _iceD_sendPrivateMessage(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
chat::chatRoom::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_chatRoom_ids, iceC_chat_chatRoom_ids + 2, s);
}

::std::vector<::std::string>
chat::chatRoom::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_chat_chatRoom_ids[0], &iceC_chat_chatRoom_ids[2]);
}

::std::string
chat::chatRoom::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::chatRoom::ice_staticId()
{
    static const ::std::string typeId = "::chat::chatRoom";
    return typeId;
}

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_listUsers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    userList ret = this->listUsers(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_join(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_nick;
    ::std::shared_ptr<UserPrx> iceP_who;
    istr->readAll(iceP_nick, iceP_who);
    inS.endReadParams();
    this->join(::std::move(iceP_nick), ::std::move(iceP_who), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_postMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_message;
    ::std::string iceP_fromWho;
    istr->readAll(iceP_message, iceP_fromWho);
    inS.endReadParams();
    this->postMessage(::std::move(iceP_message), ::std::move(iceP_fromWho), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_getUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    ::std::shared_ptr<UserPrx> ret = this->getUser(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_Leave(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    this->Leave(::std::move(iceP_name), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_chatRoom_ops, iceC_chat_chatRoom_ops + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_chatRoom_ops)
    {
        case 0:
        {
            return _iceD_Leave(in, current);
        }
        case 1:
        {
            return _iceD_getUser(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_join(in, current);
        }
        case 7:
        {
            return _iceD_listUsers(in, current);
        }
        case 8:
        {
            return _iceD_postMessage(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
chat::chatRoomFactory::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_chatRoomFactory_ids, iceC_chat_chatRoomFactory_ids + 2, s);
}

::std::vector<::std::string>
chat::chatRoomFactory::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_chat_chatRoomFactory_ids[0], &iceC_chat_chatRoomFactory_ids[2]);
}

::std::string
chat::chatRoomFactory::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::chatRoomFactory::ice_staticId()
{
    static const ::std::string typeId = "::chat::chatRoomFactory";
    return typeId;
}

/// \cond INTERNAL
bool
chat::chatRoomFactory::_iceD_newChatRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    ::std::shared_ptr<chatRoomPrx> ret = this->newChatRoom(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoomFactory::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_chatRoomFactory_ops, iceC_chat_chatRoomFactory_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_chatRoomFactory_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newChatRoom(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
chat::chatServer::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_chatServer_ids, iceC_chat_chatServer_ids + 2, s);
}

::std::vector<::std::string>
chat::chatServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_chat_chatServer_ids[0], &iceC_chat_chatServer_ids[2]);
}

::std::string
chat::chatServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::chatServer::ice_staticId()
{
    static const ::std::string typeId = "::chat::chatServer";
    return typeId;
}

/// \cond INTERNAL
bool
chat::chatServer::_iceD_getRooms(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    RoomList ret = this->getRooms(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_getRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    ::std::shared_ptr<chatRoomPrx> ret = this->getRoom(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_newChatRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    ::std::shared_ptr<chatRoomPrx> ret = this->newChatRoom(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_registerFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<chatRoomFactoryPrx> iceP_crf;
    istr->readAll(iceP_crf);
    inS.endReadParams();
    this->registerFactory(::std::move(iceP_crf), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_unregisterFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<chatRoomFactoryPrx> iceP_crf;
    istr->readAll(iceP_crf);
    inS.endReadParams();
    this->unregisterFactory(::std::move(iceP_crf), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_chatServer_ops, iceC_chat_chatServer_ops + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_chatServer_ops)
    {
        case 0:
        {
            return _iceD_getRoom(in, current);
        }
        case 1:
        {
            return _iceD_getRooms(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_newChatRoom(in, current);
        }
        case 7:
        {
            return _iceD_registerFactory(in, current);
        }
        case 8:
        {
            return _iceD_unregisterFactory(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
chat::UserPrx::_iceI_sendMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_message, const ::std::string& iceP_fromWho, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_chat_User_sendMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_message, iceP_fromWho);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::UserPrx::_iceI_sendPrivateMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_message, const ::std::string& iceP_fromWho, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_chat_User_sendPrivateMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_message, iceP_fromWho);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
chat::UserPrx::_newInstance() const
{
    return ::IceInternal::createProxy<UserPrx>();
}
/// \endcond

const ::std::string&
chat::UserPrx::ice_staticId()
{
    return User::ice_staticId();
}

/// \cond INTERNAL
void
chat::chatRoomPrx::_iceI_listUsers(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<userList>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_chat_chatRoom_listUsers_name);
    outAsync->invoke(iceC_chat_chatRoom_listUsers_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatRoomPrx::_iceI_join(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_nick, const ::std::shared_ptr<UserPrx>& iceP_who, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_chat_chatRoom_join_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_nick, iceP_who);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatRoomPrx::_iceI_postMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_message, const ::std::string& iceP_fromWho, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_chat_chatRoom_postMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_message, iceP_fromWho);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatRoomPrx::_iceI_getUser(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<UserPrx>>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_chat_chatRoom_getUser_name);
    outAsync->invoke(iceC_chat_chatRoom_getUser_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatRoomPrx::_iceI_Leave(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_chat_chatRoom_Leave_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
chat::chatRoomPrx::_newInstance() const
{
    return ::IceInternal::createProxy<chatRoomPrx>();
}
/// \endcond

const ::std::string&
chat::chatRoomPrx::ice_staticId()
{
    return chatRoom::ice_staticId();
}

/// \cond INTERNAL
void
chat::chatRoomFactoryPrx::_iceI_newChatRoom(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<chatRoomPrx>>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_chat_chatRoomFactory_newChatRoom_name);
    outAsync->invoke(iceC_chat_chatRoomFactory_newChatRoom_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
chat::chatRoomFactoryPrx::_newInstance() const
{
    return ::IceInternal::createProxy<chatRoomFactoryPrx>();
}
/// \endcond

const ::std::string&
chat::chatRoomFactoryPrx::ice_staticId()
{
    return chatRoomFactory::ice_staticId();
}

/// \cond INTERNAL
void
chat::chatServerPrx::_iceI_getRooms(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<RoomList>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_chat_chatServer_getRooms_name);
    outAsync->invoke(iceC_chat_chatServer_getRooms_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatServerPrx::_iceI_getRoom(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<chatRoomPrx>>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_chat_chatServer_getRoom_name);
    outAsync->invoke(iceC_chat_chatServer_getRoom_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatServerPrx::_iceI_newChatRoom(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<chatRoomPrx>>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_chat_chatServer_newChatRoom_name);
    outAsync->invoke(iceC_chat_chatServer_newChatRoom_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatServerPrx::_iceI_registerFactory(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<chatRoomFactoryPrx>& iceP_crf, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_chat_chatServer_registerFactory_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_crf);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
chat::chatServerPrx::_iceI_unregisterFactory(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<chatRoomFactoryPrx>& iceP_crf, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_chat_chatServer_unregisterFactory_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_crf);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
chat::chatServerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<chatServerPrx>();
}
/// \endcond

const ::std::string&
chat::chatServerPrx::ice_staticId()
{
    return chatServer::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_chat_User_sendMessage_name = "sendMessage";

const ::std::string iceC_chat_User_sendPrivateMessage_name = "sendPrivateMessage";

const ::std::string iceC_chat_chatRoom_listUsers_name = "listUsers";

const ::std::string iceC_chat_chatRoom_join_name = "join";

const ::std::string iceC_chat_chatRoom_postMessage_name = "postMessage";

const ::std::string iceC_chat_chatRoom_getUser_name = "getUser";

const ::std::string iceC_chat_chatRoom_Leave_name = "Leave";

const ::std::string iceC_chat_chatRoomFactory_newChatRoom_name = "newChatRoom";

const ::std::string iceC_chat_chatServer_getRooms_name = "getRooms";

const ::std::string iceC_chat_chatServer_getRoom_name = "getRoom";

const ::std::string iceC_chat_chatServer_newChatRoom_name = "newChatRoom";

const ::std::string iceC_chat_chatServer_registerFactory_name = "registerFactory";

const ::std::string iceC_chat_chatServer_unregisterFactory_name = "unregisterFactory";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::chat::upCast(User* p) { return p; }

void
::IceProxy::chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< User>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new User;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::chat::User::_iceI_begin_sendMessage(const ::std::string& iceP_message, const ::std::string& iceP_fromWho, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_User_sendMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_User_sendMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_message);
        ostr->write(iceP_fromWho);
        result->endWriteParams();
        result->invoke(iceC_chat_User_sendMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::chat::User::end_sendMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_chat_User_sendMessage_name);
}

::Ice::AsyncResultPtr
IceProxy::chat::User::_iceI_begin_sendPrivateMessage(const ::std::string& iceP_message, const ::std::string& iceP_fromWho, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_User_sendPrivateMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_User_sendPrivateMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_message);
        ostr->write(iceP_fromWho);
        result->endWriteParams();
        result->invoke(iceC_chat_User_sendPrivateMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::chat::User::end_sendPrivateMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_chat_User_sendPrivateMessage_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::chat::User::_newInstance() const
{
    return new User;
}
/// \endcond

const ::std::string&
IceProxy::chat::User::ice_staticId()
{
    return ::chat::User::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::chat::upCast(chatRoom* p) { return p; }

void
::IceProxy::chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< chatRoom>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new chatRoom;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::chat::chatRoom::_iceI_begin_listUsers(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_chat_chatRoom_listUsers_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatRoom_listUsers_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatRoom_listUsers_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_chat_chatRoom_listUsers_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::chat::userList
IceProxy::chat::chatRoom::end_listUsers(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_chat_chatRoom_listUsers_name);
    ::chat::userList ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::chat::chatRoom::_iceI_begin_join(const ::std::string& iceP_nick, const ::chat::UserPrx& iceP_who, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatRoom_join_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatRoom_join_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_nick);
        ostr->write(iceP_who);
        result->endWriteParams();
        result->invoke(iceC_chat_chatRoom_join_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::chat::chatRoom::end_join(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_chat_chatRoom_join_name);
}

::Ice::AsyncResultPtr
IceProxy::chat::chatRoom::_iceI_begin_postMessage(const ::std::string& iceP_message, const ::std::string& iceP_fromWho, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatRoom_postMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatRoom_postMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_message);
        ostr->write(iceP_fromWho);
        result->endWriteParams();
        result->invoke(iceC_chat_chatRoom_postMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::chat::chatRoom::end_postMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_chat_chatRoom_postMessage_name);
}

::Ice::AsyncResultPtr
IceProxy::chat::chatRoom::_iceI_begin_getUser(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_chat_chatRoom_getUser_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatRoom_getUser_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatRoom_getUser_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_chat_chatRoom_getUser_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::chat::UserPrx
IceProxy::chat::chatRoom::end_getUser(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_chat_chatRoom_getUser_name);
    ::chat::UserPrx ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::chat::chatRoom::_iceI_begin_Leave(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatRoom_Leave_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatRoom_Leave_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_chat_chatRoom_Leave_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::chat::chatRoom::end_Leave(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_chat_chatRoom_Leave_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::chat::chatRoom::_newInstance() const
{
    return new chatRoom;
}
/// \endcond

const ::std::string&
IceProxy::chat::chatRoom::ice_staticId()
{
    return ::chat::chatRoom::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::chat::upCast(chatRoomFactory* p) { return p; }

void
::IceProxy::chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< chatRoomFactory>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new chatRoomFactory;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::chat::chatRoomFactory::_iceI_begin_newChatRoom(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_chat_chatRoomFactory_newChatRoom_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatRoomFactory_newChatRoom_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatRoomFactory_newChatRoom_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_chat_chatRoomFactory_newChatRoom_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::chat::chatRoomPrx
IceProxy::chat::chatRoomFactory::end_newChatRoom(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_chat_chatRoomFactory_newChatRoom_name);
    ::chat::chatRoomPrx ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::chat::chatRoomFactory::_newInstance() const
{
    return new chatRoomFactory;
}
/// \endcond

const ::std::string&
IceProxy::chat::chatRoomFactory::ice_staticId()
{
    return ::chat::chatRoomFactory::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::chat::upCast(chatServer* p) { return p; }

void
::IceProxy::chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< chatServer>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new chatServer;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::chat::chatServer::_iceI_begin_getRooms(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_chat_chatServer_getRooms_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatServer_getRooms_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatServer_getRooms_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_chat_chatServer_getRooms_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::chat::RoomList
IceProxy::chat::chatServer::end_getRooms(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_chat_chatServer_getRooms_name);
    ::chat::RoomList ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::chat::chatServer::_iceI_begin_getRoom(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_chat_chatServer_getRoom_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatServer_getRoom_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatServer_getRoom_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_chat_chatServer_getRoom_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::chat::chatRoomPrx
IceProxy::chat::chatServer::end_getRoom(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_chat_chatServer_getRoom_name);
    ::chat::chatRoomPrx ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::chat::chatServer::_iceI_begin_newChatRoom(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_chat_chatServer_newChatRoom_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatServer_newChatRoom_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatServer_newChatRoom_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_chat_chatServer_newChatRoom_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::chat::chatRoomPrx
IceProxy::chat::chatServer::end_newChatRoom(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_chat_chatServer_newChatRoom_name);
    ::chat::chatRoomPrx ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::chat::chatServer::_iceI_begin_registerFactory(const ::chat::chatRoomFactoryPrx& iceP_crf, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatServer_registerFactory_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatServer_registerFactory_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_crf);
        result->endWriteParams();
        result->invoke(iceC_chat_chatServer_registerFactory_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::chat::chatServer::end_registerFactory(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_chat_chatServer_registerFactory_name);
}

::Ice::AsyncResultPtr
IceProxy::chat::chatServer::_iceI_begin_unregisterFactory(const ::chat::chatRoomFactoryPrx& iceP_crf, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_chat_chatServer_unregisterFactory_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_chat_chatServer_unregisterFactory_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_crf);
        result->endWriteParams();
        result->invoke(iceC_chat_chatServer_unregisterFactory_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::chat::chatServer::end_unregisterFactory(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_chat_chatServer_unregisterFactory_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::chat::chatServer::_newInstance() const
{
    return new chatServer;
}
/// \endcond

const ::std::string&
IceProxy::chat::chatServer::ice_staticId()
{
    return ::chat::chatServer::ice_staticId();
}

chat::User::~User()
{
}

/// \cond INTERNAL
::Ice::Object* chat::upCast(User* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_chat_User_ids[2] =
{
    "::Ice::Object",
    "::chat::User"
};

}

bool
chat::User::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_User_ids, iceC_chat_User_ids + 2, s);
}

::std::vector< ::std::string>
chat::User::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_chat_User_ids[0], &iceC_chat_User_ids[2]);
}

const ::std::string&
chat::User::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::User::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::chat::User";
    return typeId;
#else
    return iceC_chat_User_ids[1];
#endif
}

/// \cond INTERNAL
bool
chat::User::_iceD_sendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_message;
    ::std::string iceP_fromWho;
    istr->read(iceP_message);
    istr->read(iceP_fromWho);
    inS.endReadParams();
    this->sendMessage(iceP_message, iceP_fromWho, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::User::_iceD_sendPrivateMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_message;
    ::std::string iceP_fromWho;
    istr->read(iceP_message);
    istr->read(iceP_fromWho);
    inS.endReadParams();
    this->sendPrivateMessage(iceP_message, iceP_fromWho, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_chat_User_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendMessage",
    "sendPrivateMessage"
};

}

/// \cond INTERNAL
bool
chat::User::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_User_all, iceC_chat_User_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_User_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_sendMessage(in, current);
        }
        case 5:
        {
            return _iceD_sendPrivateMessage(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
chat::User::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< User, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
chat::User::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< User, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
chat::_icePatchObjectPtr(UserPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = UserPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(User::ice_staticId(), v);
    }
}
/// \endcond

chat::chatRoom::~chatRoom()
{
}

/// \cond INTERNAL
::Ice::Object* chat::upCast(chatRoom* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_chat_chatRoom_ids[2] =
{
    "::Ice::Object",
    "::chat::chatRoom"
};

}

bool
chat::chatRoom::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_chatRoom_ids, iceC_chat_chatRoom_ids + 2, s);
}

::std::vector< ::std::string>
chat::chatRoom::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_chat_chatRoom_ids[0], &iceC_chat_chatRoom_ids[2]);
}

const ::std::string&
chat::chatRoom::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::chatRoom::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::chat::chatRoom";
    return typeId;
#else
    return iceC_chat_chatRoom_ids[1];
#endif
}

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_listUsers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    userList ret = this->listUsers(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_join(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_nick;
    UserPrx iceP_who;
    istr->read(iceP_nick);
    istr->read(iceP_who);
    inS.endReadParams();
    this->join(iceP_nick, iceP_who, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_postMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_message;
    ::std::string iceP_fromWho;
    istr->read(iceP_message);
    istr->read(iceP_fromWho);
    inS.endReadParams();
    this->postMessage(iceP_message, iceP_fromWho, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_getUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    UserPrx ret = this->getUser(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatRoom::_iceD_Leave(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    this->Leave(iceP_name, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_chat_chatRoom_all[] =
{
    "Leave",
    "getUser",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "join",
    "listUsers",
    "postMessage"
};

}

/// \cond INTERNAL
bool
chat::chatRoom::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_chatRoom_all, iceC_chat_chatRoom_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_chatRoom_all)
    {
        case 0:
        {
            return _iceD_Leave(in, current);
        }
        case 1:
        {
            return _iceD_getUser(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_join(in, current);
        }
        case 7:
        {
            return _iceD_listUsers(in, current);
        }
        case 8:
        {
            return _iceD_postMessage(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
chat::chatRoom::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< chatRoom, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
chat::chatRoom::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< chatRoom, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
chat::_icePatchObjectPtr(chatRoomPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = chatRoomPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(chatRoom::ice_staticId(), v);
    }
}
/// \endcond

chat::chatRoomFactory::~chatRoomFactory()
{
}

/// \cond INTERNAL
::Ice::Object* chat::upCast(chatRoomFactory* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_chat_chatRoomFactory_ids[2] =
{
    "::Ice::Object",
    "::chat::chatRoomFactory"
};

}

bool
chat::chatRoomFactory::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_chatRoomFactory_ids, iceC_chat_chatRoomFactory_ids + 2, s);
}

::std::vector< ::std::string>
chat::chatRoomFactory::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_chat_chatRoomFactory_ids[0], &iceC_chat_chatRoomFactory_ids[2]);
}

const ::std::string&
chat::chatRoomFactory::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::chatRoomFactory::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::chat::chatRoomFactory";
    return typeId;
#else
    return iceC_chat_chatRoomFactory_ids[1];
#endif
}

/// \cond INTERNAL
bool
chat::chatRoomFactory::_iceD_newChatRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    chatRoomPrx ret = this->newChatRoom(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_chat_chatRoomFactory_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newChatRoom"
};

}

/// \cond INTERNAL
bool
chat::chatRoomFactory::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_chatRoomFactory_all, iceC_chat_chatRoomFactory_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_chatRoomFactory_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_newChatRoom(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
chat::chatRoomFactory::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< chatRoomFactory, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
chat::chatRoomFactory::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< chatRoomFactory, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
chat::_icePatchObjectPtr(chatRoomFactoryPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = chatRoomFactoryPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(chatRoomFactory::ice_staticId(), v);
    }
}
/// \endcond

chat::chatServer::~chatServer()
{
}

/// \cond INTERNAL
::Ice::Object* chat::upCast(chatServer* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_chat_chatServer_ids[2] =
{
    "::Ice::Object",
    "::chat::chatServer"
};

}

bool
chat::chatServer::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_chat_chatServer_ids, iceC_chat_chatServer_ids + 2, s);
}

::std::vector< ::std::string>
chat::chatServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_chat_chatServer_ids[0], &iceC_chat_chatServer_ids[2]);
}

const ::std::string&
chat::chatServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
chat::chatServer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::chat::chatServer";
    return typeId;
#else
    return iceC_chat_chatServer_ids[1];
#endif
}

/// \cond INTERNAL
bool
chat::chatServer::_iceD_getRooms(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    RoomList ret = this->getRooms(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_getRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    chatRoomPrx ret = this->getRoom(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_newChatRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    chatRoomPrx ret = this->newChatRoom(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_registerFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    chatRoomFactoryPrx iceP_crf;
    istr->read(iceP_crf);
    inS.endReadParams();
    this->registerFactory(iceP_crf, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
chat::chatServer::_iceD_unregisterFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    chatRoomFactoryPrx iceP_crf;
    istr->read(iceP_crf);
    inS.endReadParams();
    this->unregisterFactory(iceP_crf, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_chat_chatServer_all[] =
{
    "getRoom",
    "getRooms",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "newChatRoom",
    "registerFactory",
    "unregisterFactory"
};

}

/// \cond INTERNAL
bool
chat::chatServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_chat_chatServer_all, iceC_chat_chatServer_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_chat_chatServer_all)
    {
        case 0:
        {
            return _iceD_getRoom(in, current);
        }
        case 1:
        {
            return _iceD_getRooms(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_newChatRoom(in, current);
        }
        case 7:
        {
            return _iceD_registerFactory(in, current);
        }
        case 8:
        {
            return _iceD_unregisterFactory(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
chat::chatServer::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< chatServer, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
chat::chatServer::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< chatServer, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
chat::_icePatchObjectPtr(chatServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = chatServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(chatServer::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
